version: "3.6"
# Versão do docker-compose que vamos usar

volumes:
 shared-workspace:
  name: "file-system"
  driver: "local"

# volumes vai criar o sistema comum de arquivos para todos os conteiners
# Quando rodarmos distribuido, driver será network. Por enquanto é local.
# Para todos os conteiners definidos, vou avisar qual volume usarei.

services:
 spark-master:
  image: lucaspgduarte/trabalho_spark-master
  container_name: trabalho-spark-master
  ports: 
   - 8080:8080
   - 7077:7077
  volumes:
   - shared-workspace:/opt/workspace
 spark-worker-1:
  image: lucaspgduarte/trabalho_spark-worker
  container_name: trabalho-spark-worker-1
  environment:
   - SPARK_WORKER_CORES=2
   - SPARK_WORKER_MEMORY=4000m
  ports:
   - 8081:8081
  volumes:
   - shared-workspace:/opt/workspace
  depends_on:
   - spark-master
 spark-worker-2:
  image: lucaspgduarte/trabalho_spark-worker
  container_name: trabalho-spark-worker-2
  environment:
   - SPARK_WORKER_CORES=2
   - SPARK_WORKER_MEMORY=4000m
  ports:
   - 8082:8081
  volumes:
   - shared-workspace:/opt/workspace
  depends_on:
   - spark-master
 spark-worker-3:
  image: lucaspgduarte/trabalho_spark-worker
  container_name: trabalho-spark-worker-3
  environment:
   - SPARK_WORKER_CORES=2
   - SPARK_WORKER_MEMORY=4000m
  ports:
   - 8083:8081
  volumes:
   - shared-workspace:/opt/workspace
  depends_on:
   - spark-master
 spark-worker-4:
  image: lucaspgduarte/trabalho_spark-worker
  container_name: trabalho-spark-worker-4
  environment:
   - SPARK_WORKER_CORES=2
   - SPARK_WORKER_MEMORY=4000m
  ports:
   - 8084:8081
  volumes:
   - shared-workspace:/opt/workspace
  depends_on:
   - spark-master
 jupyter:
  image: ezambomsantana/jupyter
  container_name: trabalho-jupyter
  ports:
   - 8888:8888
  volumes:
   - shared-workspace:/opt/workspace

# Para cada um dos conteiners (inicialmente quatro), vamos criar um serviço.
# Preciso definir todos os conteires que vou usar, mas pode ser em qualquer ordem
# É importante dizer para o docker-compose só iniciar os workers após a criação do master